<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite ignored="0" hostname="qualitrix-thinkpad-e480" failures="1" tests="1" name="org.testscript.creator.ResourceCreation" time="107.906" errors="0" timestamp="26 Feb 2019 10:24:16 GMT" skipped="0">
  <testcase classname="org.testscript.creator.ResourceCreation" name="resourceCreation" time="107.906">
    <failure message="Failed on entering unique resource nameExpected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator &#039;By.xpath: //label[contains(.,&#039;Name&#039;)]/following::input[@type=&#039;text&#039; or @placeholder=&#039;Name&#039;]&#039; (tried for 60 second(s) with 500 milliseconds interval)" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failed on entering unique resource nameExpected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator 'By.xpath: //label[contains(.,'Name')]/following::input[@type='text' or @placeholder='Name']' (tried for 60 second(s) with 500 milliseconds interval)
	at org.testng.Assert.fail(Assert.java:94)
	at org.pageobjects.ContentCreationResourcePageObj.resourceName(ContentCreationResourcePageObj.java:1546)
	at org.testscript.creator.ResourceCreation.resourceCreation(ResourceCreation.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- resourceCreation -->
</testsuite> <!-- org.testscript.creator.ResourceCreation -->
